# Generated by Django 3.1.7 on 2021-03-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, max_length=64, verbose_name='краткое описание продукта'),
        ),
    ]
